2024-01-11 16:42:52,550: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 16:42:52,562: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:42:52,563: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:42:52,564: CryptoHandleLogger - INFO - salt bin created.
2024-01-11 16:42:52,564: HandleLogger - INFO - [test_01] - cryptodata assigned.
2024-01-11 16:42:52,568: HandleLogger - INFO - User [test_01] authentication successful.
2024-01-11 16:45:14,470: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 16:45:14,472: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:45:14,472: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:45:14,472: HandleLogger - INFO - User [test_01] authentication successful.
2024-01-11 16:46:23,903: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 16:46:23,904: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:46:23,904: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:46:23,905: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:46:23,905: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:46:23,905: HandleLogger - INFO - User [test_01] authentication successful.
2024-01-11 16:47:37,020: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:47:37,020: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:47:37,020: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:47:37,021: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:47:57,029: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:47:57,029: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:47:57,029: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:47:57,030: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:49:51,445: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:49:51,445: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:49:53,598: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:49:53,599: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:50:54,840: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:50:54,841: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:50:54,841: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:51:08,365: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:51:08,365: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:51:08,366: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:51:08,366: HandleLogger - WARNING - User [test_01] authentication unsuccessful.
2024-01-11 16:55:18,392: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:55:18,392: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:55:18,392: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:55:18,393: HandleLogger - WARNING - User [test_01] authentication unsuccessful.
2024-01-11 16:55:30,039: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:55:30,039: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:55:30,039: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:55:30,041: HandleLogger - WARNING - User [test_01] authentication unsuccessful.
2024-01-11 16:55:37,473: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:55:37,473: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:55:37,474: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:56:26,328: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:56:26,328: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:56:26,329: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:56:26,329: HandleLogger - WARNING - User [test_01] authentication unsuccessful.
2024-01-11 16:57:01,973: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:57:01,973: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:57:01,974: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:57:01,975: HandleLogger - WARNING - User [test_01] authentication unsuccessful.
2024-01-11 16:57:28,438: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:57:28,439: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:57:28,439: HandleLogger - WARNING - user: test_01 already exists.
2024-01-11 16:57:28,439: HandleLogger - WARNING - User [test_01] authentication unsuccessful.
2024-01-11 16:57:59,992: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:57:59,992: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:57:59,993: HandleLogger - WARNING - user: [test_01] already exists.
2024-01-11 16:57:59,993: HandleLogger - WARNING - User [test_01] authentication unsuccessful.
2024-01-11 16:58:04,565: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:58:04,565: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:58:04,565: HandleLogger - WARNING - user: [test_01] already exists.
2024-01-11 16:58:38,309: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 16:58:38,309: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 16:58:38,309: HandleLogger - WARNING - user: [test_01] already exists.
2024-01-11 17:05:10,219: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:05:10,219: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:05:10,220: HandleLogger - WARNING - user: [test_01] already exists.
2024-01-11 17:05:27,230: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:05:27,230: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:05:33,603: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:05:33,604: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:05:33,604: HandleLogger - WARNING - user: [test_01] already exists.
2024-01-11 17:06:52,546: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:06:52,547: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:06:52,554: HandleLogger - WARNING - user: [test_user] already exists.
2024-01-11 17:07:02,079: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:07:02,079: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:07:02,080: HandleLogger - WARNING - user: [test_user] already exists.
2024-01-11 17:07:51,910: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:07:51,910: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:07:51,910: HandleLogger - WARNING - user: [test_user] already exists.
2024-01-11 17:08:22,313: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:08:22,313: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:08:22,313: HandleLogger - WARNING - user: [test_user] already exists.
2024-01-11 17:08:22,314: HandleLogger - WARNING - User [test_user] authentication unsuccessful.
2024-01-11 17:09:32,902: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:09:32,902: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:09:32,903: HandleLogger - WARNING - User [test_user] authentication unsuccessful.
2024-01-11 17:12:30,059: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:12:30,059: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:12:30,060: HandleLogger - WARNING - User [test_user] authentication unsuccessful.
2024-01-11 17:12:35,331: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:12:35,331: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:13:02,627: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:13:02,627: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:13:07,621: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:13:07,622: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:13:07,622: HandleLogger - WARNING - User [test_user] authentication unsuccessful.
2024-01-11 17:13:45,142: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:13:45,142: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:13:45,143: HandleLogger - WARNING - User [test_user] authentication unsuccessful.
2024-01-11 17:13:51,951: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:13:51,951: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:14:43,927: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:14:43,928: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:14:43,928: HandleLogger - WARNING - User [test_user] authentication unsuccessful.
2024-01-11 17:14:48,150: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:14:48,151: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:15:09,845: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:15:09,846: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:17:22,025: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:17:22,025: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:17:39,531: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:17:39,532: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:17:47,286: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:17:47,286: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:18:07,318: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:18:07,318: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:18:13,728: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:18:13,728: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:18:36,724: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:18:36,724: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:18:55,372: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:18:55,372: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:19:06,285: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:19:06,286: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:30:49,844: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:30:49,844: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:31:24,789: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:31:24,789: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:31:24,802: MainLogger - CRITICAL - replace() argument 2 must be str, not CryptoHandler
2024-01-11 17:31:55,748: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:31:55,748: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:32:37,324: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:32:37,324: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:32:37,337: MainLogger - CRITICAL - 'CbcMode' object is not iterable
2024-01-11 17:32:54,951: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:32:54,951: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:33:58,357: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:33:58,358: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:34:31,471: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:34:31,471: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:34:44,620: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:34:44,620: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:36:34,850: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:36:34,850: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:38:04,579: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:38:04,579: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:38:14,383: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:38:14,383: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:38:26,149: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:38:26,150: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:38:33,103: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:38:33,104: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:38:38,607: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:38:38,607: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:38:56,828: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:38:56,828: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:39:15,372: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:39:15,372: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:39:21,802: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:39:21,802: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:39:28,476: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:39:28,476: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:39:51,229: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:39:51,229: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:40:08,335: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:40:08,335: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:41:32,154: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:41:32,154: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:41:50,553: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:41:50,553: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:42:23,174: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:42:23,175: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:42:35,478: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:42:35,478: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:42:48,026: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:42:48,027: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:42:59,393: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:42:59,393: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:43:21,705: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:43:21,706: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:43:57,343: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:43:57,344: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:44:00,978: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:44:00,978: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:44:32,226: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:44:32,226: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:44:34,054: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:44:34,054: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:44:46,135: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:44:46,135: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:44:47,644: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:44:47,644: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:45:39,493: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:45:39,493: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:45:40,599: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:45:40,599: ClassDataHandler - ERROR - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:50:53,264: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 17:50:53,266: ValidationLogger - INFO - [test_user] ---> Marks validated.
2024-01-11 17:50:53,266: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:50:53,266: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:50:53,267: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 17:50:53,267: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 17:50:53,273: HandleLogger - INFO - Progression stats updated.
2024-01-11 17:50:55,939: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 17:50:55,940: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:50:55,941: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:50:55,941: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 17:50:55,941: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 17:50:55,941: HandleLogger - INFO - string generated from database.
2024-01-11 17:50:55,942: HandleLogger - INFO - Key requested to dump data.
2024-01-11 17:50:55,945: CryptoHandleLogger - INFO - Key generated
2024-01-11 17:50:55,946: CryptoHandleLogger - INFO - Data bin created.
2024-01-11 17:50:55,946: HandleLogger - INFO - [test_user] - Data bin encrypted.
2024-01-11 17:50:55,947: HandleLogger - INFO - Key requested to load data.
2024-01-11 17:50:55,948: CryptoHandleLogger - INFO - Key generated
2024-01-11 17:50:55,948: CryptoHandleLogger - INFO - Key generated
2024-01-11 17:50:55,954: CryptoHandleLogger - INFO - Data retrieved from bin.
2024-01-11 17:50:55,954: CryptoHandleLogger - INFO - Data retrieved from bin.
2024-01-11 17:50:55,954: HandleLogger - INFO - [test_user] - Data bin decrypted.
2024-01-11 17:51:29,353: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 17:51:29,355: ValidationLogger - INFO - [test_user] - Marks validated.
2024-01-11 17:51:29,355: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:51:29,356: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:51:29,356: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 17:51:29,356: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 17:51:29,363: HandleLogger - INFO - Progression stats updated.
2024-01-11 17:51:30,633: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 17:51:30,634: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:51:30,634: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:51:30,635: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 17:51:30,635: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 17:51:30,635: HandleLogger - INFO - string generated from database.
2024-01-11 17:51:30,636: HandleLogger - INFO - Key requested to dump data.
2024-01-11 17:51:30,639: CryptoHandleLogger - INFO - Key generated
2024-01-11 17:51:30,640: CryptoHandleLogger - INFO - Data bin created.
2024-01-11 17:51:30,640: HandleLogger - INFO - [test_user] - Data bin encrypted.
2024-01-11 17:51:30,641: HandleLogger - INFO - Key requested to load data.
2024-01-11 17:51:30,642: CryptoHandleLogger - INFO - Key generated
2024-01-11 17:51:30,642: CryptoHandleLogger - INFO - Key generated
2024-01-11 17:51:30,648: CryptoHandleLogger - INFO - Data retrieved from bin.
2024-01-11 17:51:30,648: CryptoHandleLogger - INFO - Data retrieved from bin.
2024-01-11 17:51:30,648: HandleLogger - INFO - [test_user] - Data bin decrypted.
2024-01-11 17:52:04,796: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 17:52:04,797: ValidationLogger - INFO - [test_user] - Marks validated.
2024-01-11 17:52:04,798: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:52:04,798: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:52:04,798: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 17:52:04,799: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 17:52:04,809: HandleLogger - INFO - Progression stats updated.
2024-01-11 17:52:08,570: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 17:52:08,571: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:52:08,572: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:52:08,572: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 17:52:08,572: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 17:52:08,572: HandleLogger - INFO - string generated from database.
2024-01-11 17:52:08,573: HandleLogger - INFO - Key requested to dump data.
2024-01-11 17:52:08,576: CryptoHandleLogger - INFO - Key generated
2024-01-11 17:52:08,577: CryptoHandleLogger - INFO - Data bin created.
2024-01-11 17:52:08,578: HandleLogger - INFO - [test_user] - Data bin encrypted.
2024-01-11 17:52:08,578: HandleLogger - INFO - Key requested to load data.
2024-01-11 17:52:08,579: CryptoHandleLogger - INFO - Key generated
2024-01-11 17:52:08,579: CryptoHandleLogger - INFO - Key generated
2024-01-11 17:52:08,585: CryptoHandleLogger - INFO - Data retrieved from bin.
2024-01-11 17:52:08,585: CryptoHandleLogger - INFO - Data retrieved from bin.
2024-01-11 17:52:08,585: HandleLogger - INFO - [test_user] - Data bin decrypted.
2024-01-11 17:58:02,669: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 17:58:02,670: ValidationLogger - INFO - [test_user] - Marks validated.
2024-01-11 17:58:02,670: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:58:02,670: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:58:02,671: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 17:58:02,671: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 17:58:02,680: HandleLogger - INFO - Progression stats updated.
2024-01-11 17:58:05,238: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 17:58:05,240: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 17:58:05,240: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 17:58:05,240: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 17:58:05,241: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 17:58:05,241: HandleLogger - INFO - progress data string generated from database.
2024-01-11 17:58:05,242: HandleLogger - INFO - Key requested to dump data.
2024-01-11 17:58:05,245: CryptoHandleLogger(DEC) - INFO - Key generated
2024-01-11 17:58:05,246: CryptoHandleLogger(DEC) - INFO - Data bin created.
2024-01-11 17:58:05,246: HandleLogger - INFO - [test_user] - Data bin encrypted.
2024-01-11 17:58:05,247: HandleLogger - INFO - Key requested to load data.
2024-01-11 17:58:05,248: CryptoHandleLogger(DEC) - INFO - Key generated
2024-01-11 17:58:05,248: CryptoHandleLogger(DEC) - INFO - Key generated
2024-01-11 17:58:05,254: CryptoHandleLogger(DEC) - INFO - Data retrieved from bin.
2024-01-11 17:58:05,254: CryptoHandleLogger(DEC) - INFO - Data retrieved from bin.
2024-01-11 17:58:05,254: HandleLogger - INFO - [test_user] - Data bin decrypted.
2024-01-11 18:00:09,509: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 18:00:09,510: ValidationLogger - INFO - [test_user] - Marks validated.
2024-01-11 18:00:09,510: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 18:00:09,511: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 18:00:09,511: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 18:00:09,511: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 18:00:09,519: HandleLogger - INFO - Progression stats updated.
2024-01-11 18:00:10,599: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 18:00:10,600: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_keys/'
2024-01-11 18:00:10,600: ClassDataHandler - INFO - [WinError 183] Cannot create a file when that file already exists: 'E:\\Data\\1.Python\\3.EXPERT\\1.OOP\\progression_tracker_OOP_V2/user_data/'
2024-01-11 18:00:10,601: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 18:00:10,601: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 18:00:10,601: HandleLogger - INFO - progress data string generated from database.
2024-01-11 18:00:10,602: HandleLogger - INFO - Key requested to dump data.
2024-01-11 18:00:10,605: CryptoHandleLogger(ENC) - INFO - Key generated
2024-01-11 18:00:10,606: CryptoHandleLogger(ENC) - INFO - Data bin created.
2024-01-11 18:00:10,607: HandleLogger - INFO - [test_user] - Data bin encrypted.
2024-01-11 18:00:10,607: HandleLogger - INFO - Key requested to load data.
2024-01-11 18:00:10,608: CryptoHandleLogger(DEC) - INFO - Key generated
2024-01-11 18:00:10,614: CryptoHandleLogger(DEC) - INFO - Data retrieved from bin.
2024-01-11 18:00:10,615: HandleLogger - INFO - [test_user] - Data bin decrypted.
2024-01-11 18:03:24,378: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 18:03:24,380: ValidationLogger - INFO - [test_user] - Marks validated.
2024-01-11 18:03:24,380: ClassDataHandler - INFO - [E:\Data\1.Python\3.EXPERT\1.OOP\progression_tracker_OOP_V2/user_keys/] already exists.
2024-01-11 18:03:24,380: ClassDataHandler - INFO - [E:\Data\1.Python\3.EXPERT\1.OOP\progression_tracker_OOP_V2/user_data/] already exists.
2024-01-11 18:03:24,381: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 18:03:24,381: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 18:03:24,389: HandleLogger - INFO - Progression stats updated.
2024-01-11 18:03:25,650: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 18:03:25,651: ClassDataHandler - INFO - [E:\Data\1.Python\3.EXPERT\1.OOP\progression_tracker_OOP_V2/user_keys/] already exists.
2024-01-11 18:03:25,653: ClassDataHandler - INFO - [E:\Data\1.Python\3.EXPERT\1.OOP\progression_tracker_OOP_V2/user_data/] already exists.
2024-01-11 18:03:25,653: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 18:03:25,653: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 18:03:25,653: HandleLogger - INFO - progress data string generated from database.
2024-01-11 18:03:25,654: HandleLogger - INFO - Key requested to dump data.
2024-01-11 18:03:25,657: CryptoHandleLogger(ENC) - INFO - Key generated
2024-01-11 18:03:25,659: CryptoHandleLogger(ENC) - INFO - Data bin created.
2024-01-11 18:03:25,659: HandleLogger - INFO - [test_user] - Data bin encrypted.
2024-01-11 18:03:25,659: HandleLogger - INFO - Key requested to load data.
2024-01-11 18:03:25,660: CryptoHandleLogger(DEC) - INFO - Key generated
2024-01-11 18:03:25,667: CryptoHandleLogger(DEC) - INFO - Data retrieved from bin.
2024-01-11 18:03:25,667: HandleLogger - INFO - [test_user] - Data bin decrypted.
2024-01-11 18:04:29,112: QueryLogger - INFO - Proceeding with [default] local database [sqlite3].
2024-01-11 18:04:29,113: ClassDataHandler - INFO - Existing path found: [E:\Data\1.Python\3.EXPERT\1.OOP\progression_tracker_OOP_V2/user_keys/]
2024-01-11 18:04:29,113: ClassDataHandler - INFO - Existing path found: [E:\Data\1.Python\3.EXPERT\1.OOP\progression_tracker_OOP_V2/user_data/]
2024-01-11 18:04:29,114: HandleLogger - INFO - [test_user] existing user found.
2024-01-11 18:04:29,114: HandleLogger - INFO - User [test_user] authentication successful.
2024-01-11 18:04:29,114: HandleLogger - INFO - progress data string generated from database.
2024-01-11 18:04:29,115: HandleLogger - INFO - Key requested to dump data.
2024-01-11 18:04:29,118: CryptoHandleLogger(ENC) - INFO - Key generated
2024-01-11 18:04:29,119: CryptoHandleLogger(ENC) - INFO - Data bin created.
2024-01-11 18:04:29,119: HandleLogger - INFO - [test_user] - Data bin encrypted.
2024-01-11 18:04:29,120: HandleLogger - INFO - Key requested to load data.
2024-01-11 18:04:29,121: CryptoHandleLogger(DEC) - INFO - Key generated
2024-01-11 18:04:29,128: CryptoHandleLogger(DEC) - INFO - Data retrieved from bin.
2024-01-11 18:04:29,128: HandleLogger - INFO - [test_user] - Data bin decrypted.
